version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=db
      - DB_DATABASE=countries_cities
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - KEYCLOAK_DB_URL=jdbc:mysql://db:3306/countries_cities?serverTimezone=UTC
      - KEYCLOAK_DB_SCHEMA=public
    ports:
      - 8080:8080
    depends_on:
      - db
    command:
      - start-dev
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: countries_cities
    ports:
      - 3306:3306
    restart: unless-stopped
